### ISSUE TITLE
Example for answering NS query types?

### ISSUE THREAD

**Issue by hackeron** [johnl/powerdns_pipe#9]
I'm trying to do:

```ruby
  if question.qtype == "NS"
    answer content: question.name, type: 'NS'
  end
```

But it does not seem to be answering. Any ideas?

**Comment by hackeron** [comment]
ah, there is no question type like that, just had to add:

```ruby
  answer name: question.name, content: 'TIMELINE1.DOMAIN.ORG', type: 'NS', ttl: 86400
```

Alongside my answer answers :)

**Comment by johnl** [comment]
thanks for the report and thanks for feeding back and closing it too! :D
